# -*- coding: utf-8 -*-
"""LP 5 _7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141xUOo7E8OHC7YCXZ-SZiv5CCvo4WoR9
"""

# Importing the Boston Housing dataset from the sklearn from sklearn.datasets import load_boston boston = load_boston() #Converting the data into pandas dataframe data = pd.DataFrame(boston.data) #First look at the data data.head()

#Adding the feature names to the dataframe data.columns = boston.feature_names #Adding the target variable to the dataset data['PRICE'] = boston.target #Looking at the data with names and target variable data.head(n=10)

import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
import numpy as np

(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()

plt.imshow(x_train[1])

plt.imshow(x_train[0])

x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

x_train.shape
(60000, 28, 28)
x_test.shape
(10000, 28, 28, 1)
y_train.shape
(60000,)
y_test.shape

model = keras.Sequential([
     keras.layers.Conv2D(32, (3,3), activation='relu',input_shape=(28,28,1)),
     keras.layers.MaxPooling2D((2,2)),
     keras.layers.Dropout(0.25),
     keras.layers.Conv2D(64, (3,3), activation='relu'),
     keras.layers.MaxPooling2D((2,2)),
     keras.layers.Dropout(0.25),
     keras.layers.Conv2D(128, (3,3), activation='relu'),
     keras.layers.Flatten(),
     keras.layers.Dense(128, activation='relu'),
     keras.layers.Dropout(0.25), keras.layers.Dense(10, activation='softmax')
     ])

model.summary()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])
history = model.fit(x_train, y_train, epochs=10, validation_data=(x_test,y_test))
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

